# Generated by Django 4.1 on 2022-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_board_like_alter_board_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="content",
            field=models.JSONField(),
        ),
    ]
