# Generated by Django 4.1 on 2022-08-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                default="profile/default.png", upload_to="profile/%Y/%M/%D"
            ),
        ),
    ]
